---
title: "Night at the Movies"
type: "exercise"
description: "Model a list of movies with a custom Ruby class"
tags: "class, initialize, objects, constructors, state, behavior, instance methods"
visibility: "public"
---
